spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ai_customer_service?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
  ai:
    dashscope:
      chat:
        options:
          model: qwen-vl-plus # 聊天模型
      api-key: ${DASHSCOPE_KEY} # 密钥
      embedding:
        options:
          model: text-embedding-v4 # 向量模型
          dimensions: 2048 # 向量维度